name: 'Shave The Yak'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  pause:
    name: Get Username
    runs-on: ubuntu-latest
    run: echo "${{github.event.sender.login}}"
