name: Pause Community Contributions

on:
  push:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  pause:
    name: Pause Community Contributions
    runs-on: ubuntu-latest
    steps:
      - name: Detect if user is org member
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        id: is-organization-member
        with:
          script: |
            if (context.actor == 'dependabot' || context.actor == 'exercism-bot' || context.actor == 'github-actions[bot]') {
              return false;
            }

            return github.rest.orgs.checkMembershipForUser({
              org: "exercism",
              username: context.actor,
            }).then(response => response.status == 204)
              .catch(err => false);
      - name: Comment
        if: steps.is-organization-member.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ISSUE_COMMENT_BODY'
            })
      - name: Close
        if: steps.is-organization-member.outputs.result == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            octokit.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: "closed",
            })
