name: 'Shave The Yak'

on:
  issues:
    types: [opened]

jobs:
  shave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: check-membership
        with:
          script: |
            const result = github.rest.orgs.checkMembershipForUser({
              org: "spiky-yak",
              username: "${{ github.event.sender.login }}",
            });
            if (result.status == 204) {
              return "ok";
            }
      - name: Get result
        run: echo "${{steps.check-membership.outputs.result}}"
